resolv: Suppress clang -Wsometimes-uninitialized on getaddrinfo
clang warns that endp is used uninitialized whenever '||' condition
is true:

getaddrinfo.c:1888:11: error: variable 'endp' is used uninitialized
whenever '||' condition is true [-Werror,-Wsometimes-uninitialized]
 1888 |       && (cp == NULL
      |           ^~~~~~~~~~
getaddrinfo.c:1891:11: note: uninitialized use occurs here
 1891 |       && *endp == '\0'
      |           ^~~~
getaddrinfo.c:1888:11: note: remove the '||' if its condition is always
false
 1888 |       && (cp == NULL
      |           ^~~~~~~~~~
 1889 |           || (bits = strtoul (cp, &endp, 10)) != ULONG_MAX
      |           ~~
getaddrinfo.c:1875:13: note: initialize the variable 'endp' to silence
this warning
 1875 |   char *endp;
      |             ^
      |              = NULL
1 error generated.

However it will be evaluated after strtoul call.