stdlib: longlong.h: Do no use asm input cast for clang
clang 18 and 19 rejects the input casts with:

  error: invalid use of a cast in a inline asm context requiring an lvalue: remove the cast or build with -fheinous-gnu-extensions

While clang 20 and 21 throws a different error:

  strtod_l.c:1502:20: error: invalid use of a cast in an inline asm context requiring an lvalue
      [-Winvalid-gnu-asm-cast]

And even with -fheinous-gnu-extensions clang issues an warning
that can only be supressed with clang 20/21 (and the option might
also might be removed in the future).

On gcc the cast are still useful [1] as type-checking.

[1] https://gcc.gnu.org/pipermail/gcc-patches/2021-October/581722.html