linux: Expand internal prototypes for not-cancel.h
When building with fortify enable and with clang, internal tests
that might use not-cancel fail with:

../sysdeps/unix/sysv/linux/not-cancel.h:36:10: error: reference to overloaded function could not be resolved; did you mean to call it?
   36 | __typeof (open64) __open64_nocancel;

because clang fortify supports relies on function overload and
by having multiple function prototypes the __typeof can not
find which one to use.