i386: Fix clang build for test-fexcept-traps.c and test-fesetexcept-traps.c
Clang issues:

test-fexcept-traps.c:73:21: error: static assertion expression is not an integral constant expression
   73 |   _Static_assert (!(EXCEPTION_SET_FORCES_TRAP && !EXCEPTION_TESTS(float)),
      |   ~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   74 |                   "EXCEPTION_SET_FORCES_TRAP only makes sense if the "
      |                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   75 |                   "architecture supports exceptions");
      |                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../sysdeps/i386/fpu/math-tests-trap-force.h:27:36: note: expanded from macro 'EXCEPTION_SET_FORCES_TRAP'
   27 | #define EXCEPTION_SET_FORCES_TRAP !CPU_FEATURE_USABLE (SSE)
      |                                    ^
../sysdeps/x86/include/cpu-features.h:72:25: note: expanded from macro 'CPU_FEATURE_USABLE'
   72 |   CPU_FEATURE_USABLE_P (__get_cpu_features (), name)
      |                         ^
../sysdeps/x86/include/cpu-features.h:989:30: note: expanded from macro '__get_cpu_features'
  989 | #define __get_cpu_features() _dl_x86_get_cpu_features()
      |                              ^
note: (skipping 1 expansions in backtrace; use -fmacro-backtrace-limit=0 to see all)
../sysdeps/x86/include/cpu-features.h:61:24: note: expanded from macro 'CPU_FEATURE_ACTIVE_P'
   61 |   CPU_FEATURE_CHECK_P (ptr, natest-fesetexcept-traps.cm:e49,: 21a:c tiverror: e)static
       assertion|  expression

Because EXCEPTION_SET_FORCES_TRAP is not a constant expression.